Repository killian-mahe/shareyourproject, pull requests merged in 2020-09, with the labels that each got.

#45 Adding project public page structure + Header
  public/css/app.css
  resources/sass/app.scss
  resources/sass/components/_card.scss
  resources/sass/components/_chat.scss
  resources/sass/components/_navbar.scss
  resources/views/layouts/app.blade.php
  resources/views/project.blade.php
  resources/views/project/public.blade.php
  tailwind.config.js
Labels: UI/UX, controller, p:medium

#63 💄 Adding Project Public Page Menu
  public/css/app.css
  resources/sass/app.scss
  resources/sass/components/_nav.scss
  resources/views/layouts/app.blade.php
  resources/views/project/public.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#62 ✨ Adding badge and tags
  public/css/app.css
  public/js/app.js
  resources/js/components/utils/BadgeLabel.vue
  resources/js/components/utils/TagLabel.vue
Labels: UI/UX, enhancement, p:medium, vue-js

#66 Edit project public page structure
  resources/views/project/about.blade.php
  resources/views/project/layout.blade.php
  resources/views/project/members.blade.php
  resources/views/project/public.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#68 Adding members/about routes
  app/Http/Controllers/ProjectController.php
  public/css/app.css
  resources/sass/components/_nav.scss
  resources/views/project/layout.blade.php
  routes/web.php
Labels: enhancement, p:high

#71 Add technologies
  app/Models/Project.php
  app/User.php
  database/factories/TechnologyFactory.php
  database/migrations/2020_09_08_203121_create_technologisables_table.php
  database/seeds/DatabaseSeeder.php
Labels: database, enhancement, orm, p:high

#73 🗃 Updatin database seeding
  database/seeds/DatabaseSeeder.php
Labels: bug, database, p:medium

#74 ⬆️ Updating all the dependencies
  composer.lock
Labels: dependencies, enhancement, p:low

#77 Members project page
  app/Models/Project.php
  app/User.php
  public/css/app.css
  resources/sass/components/_card.scss
  resources/sass/components/_nav.scss
  resources/views/project/layout.blade.php
  resources/views/project/members.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#80 Add defaut profil picture and description to user
  database/factories/UserFactory.php
  database/migrations/2020_09_10_211130_add_title_users_table.php
  database/seeds/DatabaseSeeder.php
  resources/views/project/members.blade.php
Labels: bug, enhancement, p:low

#81 ✨ Adding default profile picture
  app/User.php
  public/vendor/courier/img/default_profile_picture.jpg
  resources/assets/img/default_profile_picture.jpg
  resources/views/project/members.blade.php
Labels: UI/UX, database, enhancement, orm, p:medium

#82 Laravel 8 upgrade
  app/Models/Comment.php
  app/Models/Post.php
  app/Models/Project.php
  app/Models/Tag.php
  app/Models/Technology.php
  app/User.php
  composer.json
  composer.lock
  database/factories/CommentFactory.php
  database/factories/PostFactory.php
  database/factories/ProjectFactory.php
  database/factories/TagFactory.php
  database/factories/TechnologyFactory.php
  database/factories/UserFactory.php
  database/seeders/DatabaseSeeder.php
  database/seeders/PostSeeder.php
  database/seeders/ProjectSeeder.php
  database/seeds/ProjectSeeder.php
  tests/Feature/PostTest.php
  tests/Unit/PostControllerTest.php
  tests/Unit/ProjectControllerTest.php
Labels: dependencies, enhancement, p:high

#84 💄 Adding Project About Page
  public/css/app.css
  resources/sass/components/_card.scss
  resources/views/project/about.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#85 Update user page
  app/Models/Comment.php
  app/Models/Post.php
  app/Models/Project.php
  app/Models/Tag.php
  app/Models/Technology.php
  app/User.php
  composer.json
  composer.lock
  database/factories/CommentFactory.php
  database/factories/PostFactory.php
  database/factories/ProjectFactory.php
  database/factories/TagFactory.php
  database/factories/TechnologyFactory.php
  database/factories/UserFactory.php
  database/migrations/2020_09_10_211130_add_title_users_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/PostSeeder.php
  database/seeders/ProjectSeeder.php
  database/seeds/DatabaseSeeder.php
  database/seeds/ProjectSeeder.php
  public/css/app.css
  public/vendor/courier/img/default_profile_picture.jpg
  resources/assets/img/default_profile_picture.jpg
  resources/sass/components/_card.scss
  resources/sass/components/_nav.scss
  resources/views/project/about.blade.php
  resources/views/project/layout.blade.php
  resources/views/project/members.blade.php
  tests/Feature/PostTest.php
  tests/Unit/PostControllerTest.php
  tests/Unit/ProjectControllerTest.php
Labels: wontfix

#86 Add user page header
  app/Http/Controllers/UserController.php
  resources/views/user/layout.blade.php
  resources/views/user/user.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#87 Adding user public page
  public/css/app.css
  public/js/app.js
  resources/js/components/utils/BadgeLabel.vue
  resources/sass/app.scss
  resources/sass/components/_generic.scss
  resources/sass/components/_nav.scss
  resources/views/components/cards/project.blade.php
  resources/views/components/post.blade.php
  resources/views/layouts/app.blade.php
  resources/views/project/layout.blade.php
  resources/views/project/public.blade.php
  resources/views/user/layout.blade.php
  resources/views/user/user.blade.php
  tailwind.config.js
Labels: UI/UX, enhancement, p:high, tailwindcss

#93 ♻️ Refactoring and adding blade components
  resources/views/components/cards/member.blade.php
  resources/views/project/members.blade.php
Labels: UI/UX, enhancement, p:medium

#94 🎨 Improving Scss files
  public/css/app.css
  resources/sass/components/_card.scss
  resources/sass/components/_generic.scss
  resources/sass/components/_nav.scss
  resources/views/components/cards/member.blade.php
  resources/views/project/about.blade.php
  resources/views/project/layout.blade.php
  resources/views/user/layout.blade.php
Labels: UI/UX, enhancement, p:medium, tailwindcss

#95 ♻️ Refactoring box component
  public/css/app.css
  resources/sass/components/_generic.scss
  resources/views/components/cards/member.blade.php
  resources/views/project.blade.php
  resources/views/project/layout.blade.php
  resources/views/user/layout.blade.php
  resources/views/user/user.blade.php
Labels: UI/UX, enhancement, p:medium, tailwindcss

#96 🚚 Adding Users and Projects links
  resources/views/components/cards/member.blade.php
  resources/views/components/cards/project.blade.php
  resources/views/components/post.blade.php
  resources/views/project/layout.blade.php
  resources/views/user/layout.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#98 Create vue components project user
  app/Http/Kernel.php
  app/Http/Resources/User.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  app/User.php
  composer.json
  composer.lock
  config/auth.php
  public/js/app.js
  resources/js/components/cards/MemberCard.vue
  routes/api.php
Labels: controller, enhancement, p:medium, vue-js

#102 💩 Fix Project About Page
  resources/views/project/about.blade.php
Labels: UI/UX, bug, p:high, toxic

#103 💄 Fix Nav Bar shadows
  resources/views/layouts/app.blade.php
Labels: UI/UX, enhancement, p:high, tailwindcss

#104 ✨ Adding dynamic components
  app/Http/Kernel.php
  app/Http/Resources/Project.php
  public/js/app.js
  resources/js/components/cards/ProjectCard.vue
  resources/js/components/lists/ProjectList.vue
  resources/views/components/cards/project.blade.php
  resources/views/user/user.blade.php
  routes/api.php
Labels: UI/UX, enhancement, vue-js

#106 💄 Update Button style
  public/css/app.css
  public/js/app.js
  resources/js/components/lists/ProjectList.vue
  resources/sass/components/_button.scss
  resources/sass/components/_inputs.scss
  resources/views/layouts/app.blade.php
Labels: UI/UX, enhancement, p:low, tailwindcss, vue-js

#113 ⬆️ Upgrading dependencies
  composer.lock
  package-lock.json
  package.json
Labels: bug, dependencies, p:high

#114 Create liked post
  app/Models/Post.php
  app/User.php
  database/migrations/2020_09_23_080649_create_post_user_table.php
  resources/views/components/post.blade.php
Labels: UI/UX, database, enhancement, orm, p:medium

#116 Create post vue component
  app/Http/Resources/Post.php
  public/css/app.css
  public/js/app.js
  resources/js/components/cards/PostCard.vue
  resources/views/components/post.blade.php
  routes/api.php
Labels: UI/UX, enhancement, p:medium, vue-js

#117 Refactoring UI NavBar
  public/css/app.css
  resources/sass/components/_inputs.scss
  resources/sass/components/_nav.scss
  resources/views/layouts/app.blade.php
  tailwind.config.js
Labels: UI/UX, enhancement, p:high, tailwindcss

#121 Managing routes at logging
  app/Http/Controllers/HomeController.php
  public/js/app.js
  resources/js/components/cards/MemberCard.vue
  resources/js/components/cards/PostCard.vue
  resources/js/components/cards/ProjectCard.vue
  resources/views/layouts/app.blade.php
  resources/views/layouts/auth.blade.php
Labels: UI/UX, enhancement, p:low
