Repository killian-mahe/shareyourproject, pull requests merged in 2020-08, with the labels that each got.

#8 💄 Adding auth system form
  app/Http/Controllers/Auth/RegisterController.php
  app/User.php
  composer.json
  composer.lock
  database/migrations/2020_08_17_190152_update_user_table.php
  public/css/app.css
  public/js/app.js
  public/vendor/courier/img/jeff-sheldon-8z2Q6XWLYa4.jpg
  public/vendor/courier/img/mille-sanders-Bc6qPj_f-r0.jpg
  resources/assets/img/jeff-sheldon-8z2Q6XWLYa4.jpg
  resources/assets/img/mille-sanders-Bc6qPj_f-r0.jpg
  resources/js/components/inputs/CustomInput.vue
  resources/js/components/inputs/InputLabel.vue
  resources/js/components/inputs/SelectInput.vue
  resources/sass/app.scss
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/home.blade.php
Labels: enhancement

#12 🐛 Removing navbar in auth views
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/verify.blade.php
  resources/views/layouts/auth.blade.php
Labels: UI/UX, bug

#13 Adding previous value in auth forms
  public/js/app.js
  resources/js/components/inputs/CustomInput.vue
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
Labels: UI/UX, enhancement

#15 🚧 Creating 2nd NavBar
  public/css/app.css
  resources/sass/app.scss
  resources/views/layouts/app.blade.php
Labels: UI/UX, enhancement

#17 💄 TailWindCSS Adapt
  public/css/app.css
  resources/sass/app.scss
  tailwind.config.js
Labels: UI/UX, enhancement

#18 🍻 Fix NavBar Button Animation
  public/css/app.css
  resources/sass/app.scss
Labels: bug, toxic

#20 🍻 Fix Search-Input
  public/css/app.css
  resources/sass/app.scss
Labels: bug, toxic

#21 Add basic model
  app/Models/Comment.php
  app/Models/Post.php
  app/Models/Project.php
  app/Models/Tag.php
  app/Models/Technology.php
  database/migrations/2020_08_20_184132_add_technologies_table.php
  database/migrations/2020_08_20_191532_add_tags_table.php
  database/migrations/2020_08_20_193008_create_projects_table.php
  database/migrations/2020_08_20_200845_create_taggables_table.php
  database/migrations/2020_08_20_204240_create_posts_table.php
  database/migrations/2020_08_20_210029_create_comments_table.php
Labels: database, enhancement

#29 ✨ Adding main controllers and tests
  .github/workflows/laravel.yml
  app/Http/Controllers/PostController.php
  app/User.php
  database/factories/UserFactory.php
  routes/web.php
  tests/Feature/PostTest.php
Labels: enhancement, test

#32 UI real time chat
  public/css/app.css
  public/vendor/courier/icons/close-cultured-100.svg
  public/vendor/courier/icons/minus-cultured-100.svg
  public/vendor/courier/icons/search-cultured-100.svg
  public/vendor/courier/icons/send-cultured-100.svg
  public/vendor/courier/icons/send2-cultured-100.svg
  public/vendor/courier/icons/smiley-cultured-100.svg
  public/vendor/courier/icons/user-cultured-100.svg
  resources/assets/icons/close-cultured-100.svg
  resources/assets/icons/minus-cultured-100.svg
  resources/assets/icons/search-cultured-100.svg
  resources/assets/icons/send-cultured-100.svg
  resources/assets/icons/send2-cultured-100.svg
  resources/assets/icons/smiley-cultured-100.svg
  resources/sass/app.scss
  resources/views/layouts/app.blade.php
  tailwind.config.js
Labels: UI/UX, enhancement, tailwindcss

#38 Refactoring CSS
  package-lock.json
  package.json
  public/css/app.css
  public/vendor/courier/icons/close-cultured-100.svg
  public/vendor/courier/icons/minus-cultured-100.svg
  public/vendor/courier/icons/search-cultured-100.svg
  public/vendor/courier/icons/send-cultured-100.svg
  public/vendor/courier/icons/send2-cultured-100.svg
  public/vendor/courier/icons/smiley-cultured-100.svg
  public/vendor/courier/icons/tool-white.svg
  public/vendor/courier/icons/tool.svg
  public/vendor/courier/icons/user-cultured-100.svg
  resources/assets/icons/close-cultured-100.svg
  resources/assets/icons/minus-cultured-100.svg
  resources/assets/icons/search-cultured-100.svg
  resources/assets/icons/send-cultured-100.svg
  resources/assets/icons/send2-cultured-100.svg
  resources/assets/icons/smiley-cultured-100.svg
  resources/assets/icons/tool-white.svg
  resources/assets/icons/tool.svg
  resources/sass/app.scss
  resources/views/layouts/app.blade.php
  tailwind.config.js
Labels: UI/UX, bug, enhancement, tailwindcss

#40 🍻 Toxic Dev
  public/css/app.css
Labels: toxic

#37 Create post project factories
  app/Http/Controllers/PostController.php
  database/factories/PostFactory.php
  database/factories/ProjectFactory.php
  tests/Feature/PostTest.php
Labels: database, test

#43 🗃 Renaming author column to owner
  app/Models/Project.php
  database/migrations/2020_08_25_211011_rename_project_owner_field.php
Labels: bug, database, orm

#44 🗃 Update User model relationships
  app/User.php
Labels: bug, orm

#47 Adding factories and seeding
  .github/workflows/laravel.yml
  app/User.php
  database/factories/CommentFactory.php
  database/factories/TagFactory.php
  database/factories/UserFactory.php
  database/seeds/DatabaseSeeder.php
  database/seeds/PostSeeder.php
  database/seeds/ProjectSeeder.php
Labels: database, enhancement, orm, test

#51 ♻️ Refactoring style file structure
  resources/sass/app.scss
  resources/sass/components/_button.scss
  resources/sass/components/_card.scss
  resources/sass/components/_chat.scss
  resources/sass/components/_inputs.scss
Labels: UI/UX, enhancement, tailwindcss

#55 Add user project relationship
  app/Models/Project.php
  app/User.php
  database/migrations/2020_08_30_193833_create_project_user_table.php
Labels: database, orm, p:high

#56 Add comment controller
  app/Http/Controllers/CommentController.php
  routes/web.php
  tests/Unit/CommentControllerTest.php
Labels: controller, p:medium, test
